apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
  volumeMode: Filesystem
